=== servicosgovbr/cartas-de-servico/cartas-servico/v3/servico.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://servicos.gov.br/v3/schema"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://servicos.gov.br/v3/schema"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified"
           version="1.0">

    <xs:element name="servico" type="Servico"/>
    <xs:complexType name="Servico">
        <xs:sequence>
            <xs:element name="nome" type="NomeDoServico"/>
            <xs:element name="sigla" type="Sigla"/>
            <xs:element name="nomes-populares" type="NomesPopulares"/>
            <xs:element name="descricao" type="DescricaoDoServico"/>
            <xs:element name="gratuito" type="Gratuito"/>
            <xs:element name="solicitantes" type="Solicitantes"/>
            <xs:element name="tempo-total-estimado" type="TempoTotalEstimado"/>
            <xs:element name="etapas" type="Etapas"/>
            <xs:element name="orgao" type="Orgao"/>
            <xs:element name="segmentos-da-sociedade" type="SegmentosDaSociedade"/>
            <xs:element name="eventos-da-linha-da-vida" type="EventosDaLinhaDaVida"/>
            <xs:element name="areas-de-interesse" type="AreasDeInteresse"/>
            <xs:element name="palavras-chave" type="PalavrasChave"/>
            <xs:element name="legislacoes" type="Legislacoes"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="NomeDoServico">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:simpleType name="Sigla">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:complexType name="NomesPopulares">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="item" type="NomePopular"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="NomePopular">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:simpleType name="DescricaoDoServico">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:simpleType name="Gratuito">
        <xs:restriction base="xs:string">
            <xs:enumeration value=""/>
            <xs:enumeration value="true"/>
            <xs:enumeration value="false"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="Solicitantes">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="solicitante" type="Solicitante"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Solicitante">
        <xs:sequence>
            <xs:element name="tipo" type="TipoDeSolicitante"/>
            <xs:element name="requisitos" type="Requisitos"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="TipoDeSolicitante">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:simpleType name="Requisitos">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:complexType name="TempoTotalEstimado">
        <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="1">
                <xs:element name="entre" type="Entre"/>
                <xs:element name="ate" type="Ate"/>
            </xs:choice>
            <xs:element name="descricao" type="DescricaoDoTempoTotalEstimado"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Entre">
        <xs:attribute name="min" type="UnidadeDeTempo" use="required"/>
        <xs:attribute name="max" type="UnidadeDeTempo" use="required"/>
        <xs:attribute name="unidade" type="TipoDeTempoTotalEstimado" use="required"/>
    </xs:complexType>

    <xs:complexType name="Ate">
        <xs:attribute name="max" type="UnidadeDeTempo" use="required"/>
        <xs:attribute name="unidade" type="TipoDeTempoTotalEstimado" use="required"/>
    </xs:complexType>

    <xs:simpleType name="TipoDeTempoTotalEstimado">
        <xs:restriction base="xs:string">
            <xs:enumeration value="minutos"/>
            <xs:enumeration value="horas"/>
            <xs:enumeration value="dias"/>
            <xs:enumeration value="dias-corridos"/>
            <xs:enumeration value="dias-uteis"/>
            <xs:enumeration value="meses"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="UnidadeDeTempo">
        <xs:restriction base="xs:nonNegativeInteger"/>
    </xs:simpleType>

    <xs:simpleType name="DescricaoDoTempoTotalEstimado">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:complexType name="Etapas">
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="etapa" type="Etapa"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Etapa">
        <xs:sequence>
            <xs:element name="titulo" type="Titulo"/>
            <xs:element name="descricao" type="DescricaoDaEtapa"/>
            <xs:element name="documentos" type="Documentos"/>
            <xs:element name="custos" type="Custos"/>
            <xs:element name="canais-de-prestacao" type="CanaisDePrestacao"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="Titulo">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:simpleType name="DescricaoDaEtapa">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:complexType name="Documentos">
        <xs:sequence>
            <xs:element name="default" type="CasoDeDocumentos"/>
            <xs:element name="caso" type="CasoDeDocumentos" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="CasoDeDocumentos">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="item" type="Documento"/>
        </xs:sequence>
        <xs:attribute name="descricao" type="xs:string" use="optional"/>
    </xs:complexType>

    <xs:simpleType name="Documento">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:complexType name="Custos">
        <xs:sequence>
            <xs:element name="default" type="CasoDeCustos"/>
            <xs:element name="caso" type="CasoDeCustos" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="CasoDeCustos">
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="custo" type="Custo" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="descricao" type="xs:string" use="optional"/>
    </xs:complexType>

    <xs:complexType name="Custo">
        <xs:sequence>
            <xs:element name="descricao" type="DescricaoDoCusto"/>
            <xs:element name="moeda" type="Moeda"/>
            <xs:element name="valor" type="Valor"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="DescricaoDoCusto">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:simpleType name="Moeda">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:simpleType name="Valor">
        <xs:restriction base="xs:string"/>
        <!-- TODO: restringir usando expressão regular para aceitar números e vírgula separando os centavos -->
    </xs:simpleType>

    <xs:complexType name="CanaisDePrestacao">
        <xs:sequence>
            <xs:element name="default" type="CasoDeCanaisDePrestacao"/>
            <xs:element name="caso" type="CasoDeCanaisDePrestacao" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="CasoDeCanaisDePrestacao">
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="canal-de-prestacao" type="CanalDePrestacao"/>
        </xs:sequence>
        <xs:attribute name="descricao" type="xs:string" use="optional"/>
    </xs:complexType>

    <xs:complexType name="CanalDePrestacao">
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="descricao" type="DescricaoDeCanalDePrestacao"/>
        </xs:sequence>
        <xs:attribute name="tipo" type="TipoDeCanalDePrestacao" use="required"/>
    </xs:complexType>

    <xs:simpleType name="DescricaoDeCanalDePrestacao">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:simpleType name="TipoDeCanalDePrestacao">
        <xs:restriction base="xs:string">
            <xs:enumeration value="web"/>
            <xs:enumeration value="web-agendar"/>
            <xs:enumeration value="web-inscrever-se"/>
            <xs:enumeration value="web-simular"/>
            <xs:enumeration value="web-calcular-taxas"/>
            <xs:enumeration value="web-acompanhar"/>
            <xs:enumeration value="web-consultar"/>
            <xs:enumeration value="web-emitir"/>
            <xs:enumeration value="web-preencher"/>
            <xs:enumeration value="web-declarar"/>
            <xs:enumeration value="presencial"/>
            <xs:enumeration value="telefone"/>
            <xs:enumeration value="e-mail"/>
            <xs:enumeration value="postal"/>
            <xs:enumeration value="aplicativo-movel"/>
            <xs:enumeration value="sms"/>
            <xs:enumeration value="fax"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="Orgao">
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="SegmentosDaSociedade">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="item" type="SegmentoDaSociedade"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="SegmentoDaSociedade">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Cidadãos"/>
            <xs:enumeration value="Empresas"/>
            <xs:enumeration value="Órgãos e entidades públicas"/>
            <xs:enumeration value="Demais segmentos (ONGs, organizações sociais, etc)"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="EventosDaLinhaDaVida">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="item" type="EventoDaLinhaDaVida"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="EventoDaLinhaDaVida">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Apoio financeiro e crédito"/>
            <xs:enumeration value="Aposentadoria"/>
            <xs:enumeration value="Contas e Impostos"/>
            <xs:enumeration value="Cuidados com a saúde"/>
            <xs:enumeration value="Documentos e certidões"/>
            <xs:enumeration value="Empreendedorismo e negócios"/>
            <xs:enumeration value="Estrangeiros no Brasil"/>
            <xs:enumeration value="Estudos"/>
            <xs:enumeration value="Exportação de produtos e serviços"/>
            <xs:enumeration value="Família"/>
            <xs:enumeration value="Importação de produtos e serviços"/>
            <xs:enumeration value="Imóveis"/>
            <xs:enumeration value="Profissão e trabalho"/>
            <xs:enumeration value="Veículos"/>
            <xs:enumeration value="Viagem ao exterior"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="AreasDeInteresse">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="item" type="AreaDeInteresse"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="AreaDeInteresse">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Abastecimento"/>
            <xs:enumeration value="Administração financeira"/>
            <xs:enumeration value="Agricultura orgânica"/>
            <xs:enumeration value="Agropecuária"/>
            <xs:enumeration value="Águas"/>
            <xs:enumeration value="Alimento"/>
            <xs:enumeration value="Ambiente e saúde"/>
            <xs:enumeration value="Comunicações"/>
            <xs:enumeration value="Comércio e Serviços"/>
            <xs:enumeration value="Economia e Finanças"/>
            <xs:enumeration value="Educação"/>
            <xs:enumeration value="Educação básica"/>
            <xs:enumeration value="Educação superior"/>
            <xs:enumeration value="Educação à distância"/>
            <xs:enumeration value="Emergências e Urgências"/>
            <xs:enumeration value="Encargos financeiros"/>
            <xs:enumeration value="Esporte e Lazer"/>
            <xs:enumeration value="Finanças"/>
            <xs:enumeration value="Habitação"/>
            <xs:enumeration value="Humanização na saúde"/>
            <xs:enumeration value="Indústria"/>
            <xs:enumeration value="Meio ambiente"/>
            <xs:enumeration value="Pecuária"/>
            <xs:enumeration value="Pessoa"/>
            <xs:enumeration value="Previdência Social"/>
            <xs:enumeration value="Profissionais da educação"/>
            <xs:enumeration value="Proteção social"/>
            <xs:enumeration value="Qualidade ambiental"/>
            <xs:enumeration value="Relações Internacionais"/>
            <xs:enumeration value="Saúde"/>
            <xs:enumeration value="Saúde da criança"/>
            <xs:enumeration value="Saúde da família"/>
            <xs:enumeration value="Saúde da mulher"/>
            <xs:enumeration value="Saúde do homem"/>
            <xs:enumeration value="Saúde do idoso"/>
            <xs:enumeration value="Saúde dos portadores de deficiências"/>
            <xs:enumeration value="Segurança e Ordem Pública"/>
            <xs:enumeration value="Trabalho"/>
            <xs:enumeration value="Transportes"/>
            <xs:enumeration value="Turismo"/>
            <xs:enumeration value="Urbanismo"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="PalavrasChave">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="item" type="PalavraChave"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="PalavraChave">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:complexType name="Legislacoes">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="item" type="Legislacao"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="Legislacao">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

</xs:schema>

=== servicosgovbr/cartas-de-servico/cartas-servico/v3/servicos/melhor-em-casa-assistencia-domiciliar.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<servico xmlns="http://servicos.gov.br/v3/schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://servicos.gov.br/v3/schema ../servico.xsd">
    <nome>Melhor em Casa - Assistência Domiciliar</nome>
    <sigla/>
    <nomes-populares/>
    <descricao>Pessoas com necessidade de reabilitação motora, idosos, pacientes crônicos sem agravamento ou em situação pós-cirúrgica, por exemplo, terão assistência multiprofissional gratuita em seus lares, com cuidados mais próximos da família.

O atendimento será feito por equipes multidisciplinares, formadas prioritariamente por médicos, enfermeiros, técnicos em enfermagem e fisioterapeuta. Outros profissionais (fonoaudiólogo, nutricionista, odontólogo, psicólogo e farmacêutico) poderão compor as equipes de apoio. Cada equipe poderá atender, em média, 60 pacientes, simultaneamente.</descricao>
    <gratuito/>
    <solicitantes/>
    <tempo-total-estimado>
        <descricao/>
    </tempo-total-estimado>
    <etapas>
        <etapa>
            <titulo/>
            <descricao/>
            <documentos>
                <default/>
            </documentos>
            <custos>
                <default/>
            </custos>
            <canais-de-prestacao>
                <default>
                    <canal-de-prestacao tipo="web">
                        <descricao>http://sage.saude.gov.br/?link=melhorCasa&amp;flt=true&amp;param=null</descricao>
                    </canal-de-prestacao>
                </default>
            </canais-de-prestacao>
        </etapa>
    </etapas>
    <orgao id="http://estruturaorganizacional.dados.gov.br/id/unidade-organizacional/304"/>
    <segmentos-da-sociedade/>
    <areas-de-interesse>
        <item>Humanização na saúde</item>
        <item>Saúde</item>
        <item>Saúde dos portadores de deficiências</item>
    </areas-de-interesse>
    <palavras-chave/>
    <legislacoes/>
</servico>

=== servicosgovbr/cartas-de-servico/cartas-servico/v3/servicos/entrega-voluntaria-de-armas-de-fogo-campanha-nacional-do-desarmamento.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<servico xmlns="http://servicos.gov.br/v3/schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://servicos.gov.br/v3/schema ../servico.xsd">
    <nome>Entrega voluntária de armas de fogo - Campanha Nacional do Desarmamento</nome>
    <sigla/>
    <nomes-populares/>
    <descricao>Os proprietários ou possuidores de arma(s) de fogo, com ou sem registro, podem entregá-la(s) à Polícia Federal ou às instituições credenciadas para destruição. Ao entregar uma arma, o cidadão não precisará se identificar e receberá indenização que varia de R$ 150,00 a R$ 450,00, conforme o tipo da arma entregue.

A Campanha Nacional do Desarmamento busca a mobilização da sociedade brasileira para retirar de circulação o maior número possível de armas de fogo. A entrega é voluntária e pode ser feita em mais de 2 mil postos de coleta em todo o Brasil.

Para a entrega de uma arma, o cidadão deverá seguir os seguintes procedimentos:

1. Acessar o site da Campanha e emitir a guia de trânsito (Vide "Emissão da guia de trânsito");
2. Dirigir-se até um posto credenciado de entrega voluntária (Vide "Localize o posto de entrega voluntária de armas mais próximo de você") com a guia de trânsito e a arma desmuniciada (descarregada) e embalada, bem como documento de registro de arma de fogo (caso disponível);
3. Ao efetuar a entrega, o agente de segurança fará o recebimento via Sistema Desarma e solicitará ao cidadão o cadastramento de uma senha com 4 dígitos para recebimento da indenização;
4. Finalizado o cadastro via sistema, o cidadão receberá um documento de entrega da arma, que conterá um código de indenização com 16 dígitos;
5. Após 24h da entrega e no prazo máximo de 30 dias, o cidadão deverá se dirigir a um autoatendimento do Banco do Brasil para o saque da indenização. Para isso, é necessário apenas o código de indenização (16 dígitos) e a senha cadastrada (4 dígitos);

* [Mais informações](undefined): Qualquer problema no processo deverá ser comunicado por e-mail: desarmamento@mj.gov.br

* [Telefone](undefined): (61) 2025-9125

* [Formulários](http://desarma.mj.gov.br/SisDesarmamento/formulario/portador.do): Emissão da Guia de Trânsito

* [Serviços relacionados](http://www.dpf.gov.br/servicos/armas/comunicacao-de-ocorrencias): Comunicação de ocorrências envolvendo Arma de Fogo

* [Mais informações](http://www.dpf.gov.br/servicos/armas/): Sobre Armas de Fogo</descricao>
    <gratuito/>
    <solicitantes/>
    <tempo-total-estimado>
        <descricao/>
    </tempo-total-estimado>
    <etapas>
        <etapa>
            <titulo/>
            <descricao/>
            <documentos>
                <default/>
            </documentos>
            <custos>
                <default/>
            </custos>
            <canais-de-prestacao>
                <default>
                    <canal-de-prestacao tipo="web">
                        <descricao>http://www.dpf.gov.br/simba/armas/campanha-do-desarmamento/entrega-de-arma-de-fogo</descricao>
                    </canal-de-prestacao>
                </default>
            </canais-de-prestacao>
        </etapa>
    </etapas>
    <orgao id="http://estruturaorganizacional.dados.gov.br/id/unidade-organizacional/316"/>
    <segmentos-da-sociedade>
        <item>Cidadãos</item>
    </segmentos-da-sociedade>
    <areas-de-interesse>
        <item>Proteção social</item>
    </areas-de-interesse>
    <palavras-chave/>
    <legislacoes/>
</servico>

=== servicosgovbr/cartas-de-servico/conteudo/servicos/consulta-parcelamentos-deferidos-no-ambito-da-receita-federal.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<servico xmlns="http://servicos.gov.br/v3/schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://servicos.gov.br/v3/schema ../servico.xsd">
    <nome>Consulta Parcelamentos Deferidos no Âmbito da Receita Federal</nome>
    <sigla/>
    <nomes-populares/>
    <descricao>Consultar relação de parcelamentos concedidos no âmbito da Receita Federal por contribuinte.</descricao>
    <gratuito/>
    <solicitantes/>
    <tempo-total-estimado>
        <descricao/>
    </tempo-total-estimado>
    <etapas>
        <etapa>
            <titulo/>
            <descricao/>
            <documentos>
                <default/>
            </documentos>
            <custos>
                <default/>
            </custos>
            <canais-de-prestacao>
                <default>
                    <canal-de-prestacao tipo="web">
                        <descricao>http://www.receita.fazenda.gov.br/Aplicacoes/ATSPO/Parcelamento/default.htm</descricao>
                    </canal-de-prestacao>
                </default>
            </canais-de-prestacao>
        </etapa>
    </etapas>
    <orgao id="http://estruturaorganizacional.dados.gov.br/id/unidade-organizacional/77"/>
    <segmentos-da-sociedade>
        <item>Cidadãos</item>
        <item>Empresas</item>
    </segmentos-da-sociedade>
    <areas-de-interesse>
        <item>Economia e Finanças</item>
    </areas-de-interesse>
    <palavras-chave/>
    <legislacoes/>
</servico>

=== servicosgovbr/cartas-de-servico/cartas-servico/v3/servicos/obter-autorizacao-da-ancine-para-realizar-filmagem-estrangeira-no-brasil.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<servico xsi:schemaLocation="http://servicos.gov.br/v3/schema.../servico.xsd" xmlns="http://servicos.gov.br/v3/schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <id>obter-autorizacao-da-ancine-para-realizar-filmagem-estrangeira-no-brasil</id>
    <dbId>4164</dbId>
    <nome>Obter autorização da ANCINE para realizar filmagem estrangeira no Brasil</nome>
    <sigla></sigla>
    <nomes-populares>
        <item id="3182">Filmagem Estrangeira no Brasil</item>
    </nomes-populares>
    <descricao>Recebimento e processamento das comunicações de filmagem/produção de obras estrangeiras a serem realizadas no território nacional. A comunicação é realizada por empresa produtora brasileira registrada na ANCINE que possua instrumento contratual firmado com a empresa produtora estrangeira.</descricao>
    <contato></contato>
    <gratuito>true</gratuito>
    <porcentagem-manual>false</porcentagem-manual>
    <servico-digital>false</servico-digital>
    <link-servico-digital></link-servico-digital>
    <solicitantes>
        <solicitante id="5169">
            <tipo>Produtores de filmagem.</tipo>
            <requisitos>Requisitos necessários para o solicitante:

- Registro de produtora brasileira junto à ANCINE; 
- Instrumento contratual entre a empresa produtora estrangeira e a empresa produtora brasileira.</requisitos>
        </solicitante>
    </solicitantes>
    <tempo-total-estimado>
        <ate max="5" unidade="dias-uteis"/>
        <descricao></descricao>
    </tempo-total-estimado>
    <validade-documento>
        <descricao></descricao>
    </validade-documento>
    <etapas>
        <etapa id="9287">
            <titulo>Solicitação de Filmagem Estrangeira no Brasil</titulo>
            <descricao>Envio de requerimento próprio, intitulado “Comunicação de Produção de Obra Audiovisual Estrangeira em Território Nacional[LMLG1] ”,acompanhado da documentação listada no art. 2º da Instrução Normativa nº 79 da ANCINE, de 15/10/2008;
Análise da documentação pelo setor responsável;
Acatamento da comunicação, rejeição ou formulação de exigências;
Emissão de ofício, certificando a comunicação, se houver acatamento;
Envio do ofício à produtora brasileira e às competentes representações</descricao>
            <documentos>
                <default>
                    <item id="13483">Formulário de comunicação de produção de obra audiovisual estrangeira no território nacional, anexo à Instrução Normativa nº 79 e disponível em http://www.ancine.gov.br/media/Formulario1IN79art2.doc;</item>
                    <item id="13484">Cópia do contrato firmado entre a empresa produtora estrangeira, ou responsável legal pelo empreendimento, e a empresa produtora brasileira, com indicação das responsabilidades recíprocas, forma de remuneração acordada e o período de validade do instrumento; 
Cópia da tradução do contrato acima citado, quando em idioma estrangeiro;</item>
                    <item id="13485">Plano provisório de filmagem/gravação, com a indicação de datas e dos locais (Município/UF), no território brasileiro, onde se realizarão os trabalhos; 
Cópia das folhas de identificação do passaporte de cada profissional estrangeiro.</item>
                </default>
            </documentos>
            <custos>
                <default/>
            </custos>
            <tempo-total-estimado>
                <ate max="5" unidade="dias-uteis"/>
            </tempo-total-estimado>
            <canais-de-prestacao>
                <default>
                    <canal-de-prestacao id="10166" tipo="e-mail">
                        <descricao>filmagem.estrangeira@ancine.gov.br</descricao>
                    </canal-de-prestacao>
                </default>
            </canais-de-prestacao>
        </etapa>
    </etapas>
    <orgao id="http://estruturaorganizacional.dados.gov.br/id/unidade-organizacional/57682" dbId="916">
        <nomeOrgao>Agência Nacional do Cinema (ANCINE)</nomeOrgao>
    </orgao>
    <segmentos-da-sociedade>
        <item idSegmento="3" idServicoSegmento="8989">Empresas</item>
    </segmentos-da-sociedade>
    <areas-de-interesse>
        <item>Difusão Cultural</item>
        <item>Cooperação Internacional</item>
        <item>Relações Internacionais</item>
        <item>Cultura</item>
    </areas-de-interesse>
    <palavras-chave>
        <item id="17094">Filmagem Estrangeira no Brasil</item>
        <item id="17095">produção audiovisual estrangeira no Brasil</item>
        <item id="17096">produção audiovisual brasileira com participa</item>
        <item id="17097">filmagem estrangeira no país</item>
    </palavras-chave>
    <legislacoes>
        <item id="3099">Instrução Normativa nº 79 da ANCINE, de 15 de outubro de 2008</item>
    </legislacoes>
    <condicoes-acessibilidade>..</condicoes-acessibilidade>
    <tratamento-prioritario>..</tratamento-prioritario>
    <tratamento-dispensado-atendimento>Esse serviço não se aplica a produções estrangeiras de obra jornalística. O ofício também é produzido no caso de filmagens brasileiras que envolvam a participação de profissionais estrangeiros, de forma a facilitar a emissão do visto para estes profissionais.</tratamento-dispensado-atendimento>
</servico>
