=== servicosgovbr/cartas-de-servico/cartas-servico/v3/servico.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://servicos.gov.br/v3/schema"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://servicos.gov.br/v3/schema"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified"
           version="1.0">

    <xs:element name="servico" type="Servico"/>
    <xs:complexType name="Servico">
        <xs:sequence>
            <xs:element name="nome" type="NomeDoServico"/>
            <xs:element name="sigla" type="Sigla"/>
            <xs:element name="nomes-populares" type="NomesPopulares"/>
            <xs:element name="descricao" type="DescricaoDoServico"/>
            <xs:element name="gratuito" type="Gratuito"/>
            <xs:element name="solicitantes" type="Solicitantes"/>
            <xs:element name="tempo-total-estimado" type="TempoTotalEstimado"/>
            <xs:element name="etapas" type="Etapas"/>
            <xs:element name="orgao" type="Orgao"/>
            <xs:element name="segmentos-da-sociedade" type="SegmentosDaSociedade"/>
            <xs:element name="eventos-da-linha-da-vida" type="EventosDaLinhaDaVida"/>
            <xs:element name="areas-de-interesse" type="AreasDeInteresse"/>
            <xs:element name="palavras-chave" type="PalavrasChave"/>
            <xs:element name="legislacoes" type="Legislacoes"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="NomeDoServico">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:simpleType name="Sigla">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:complexType name="NomesPopulares">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="item" type="NomePopular"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="NomePopular">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:simpleType name="DescricaoDoServico">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:simpleType name="Gratuito">
        <xs:restriction base="xs:string">
            <xs:enumeration value=""/>
            <xs:enumeration value="true"/>
            <xs:enumeration value="false"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="Solicitantes">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="solicitante" type="Solicitante"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Solicitante">
        <xs:sequence>
            <xs:element name="tipo" type="TipoDeSolicitante"/>
            <xs:element name="requisitos" type="Requisitos"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="TipoDeSolicitante">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:simpleType name="Requisitos">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:complexType name="TempoTotalEstimado">
        <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="1">
                <xs:element name="entre" type="Entre"/>
                <xs:element name="ate" type="Ate"/>
            </xs:choice>
            <xs:element name="descricao" type="DescricaoDoTempoTotalEstimado"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Entre">
        <xs:attribute name="min" type="UnidadeDeTempo" use="required"/>
        <xs:attribute name="max" type="UnidadeDeTempo" use="required"/>
        <xs:attribute name="unidade" type="TipoDeTempoTotalEstimado" use="required"/>
    </xs:complexType>

    <xs:complexType name="Ate">
        <xs:attribute name="max" type="UnidadeDeTempo" use="required"/>
        <xs:attribute name="unidade" type="TipoDeTempoTotalEstimado" use="required"/>
    </xs:complexType>

    <xs:simpleType name="TipoDeTempoTotalEstimado">
        <xs:restriction base="xs:string">
            <xs:enumeration value="minutos"/>
            <xs:enumeration value="horas"/>
            <xs:enumeration value="dias"/>
            <xs:enumeration value="dias-corridos"/>
            <xs:enumeration value="dias-uteis"/>
            <xs:enumeration value="meses"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="UnidadeDeTempo">
        <xs:restriction base="xs:nonNegativeInteger"/>
    </xs:simpleType>

    <xs:simpleType name="DescricaoDoTempoTotalEstimado">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:complexType name="Etapas">
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="etapa" type="Etapa"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Etapa">
        <xs:sequence>
            <xs:element name="titulo" type="Titulo"/>
            <xs:element name="descricao" type="DescricaoDaEtapa"/>
            <xs:element name="documentos" type="Documentos"/>
            <xs:element name="custos" type="Custos"/>
            <xs:element name="canais-de-prestacao" type="CanaisDePrestacao"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="Titulo">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:simpleType name="DescricaoDaEtapa">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:complexType name="Documentos">
        <xs:sequence>
            <xs:element name="default" type="CasoDeDocumentos"/>
            <xs:element name="caso" type="CasoDeDocumentos" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="CasoDeDocumentos">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="item" type="Documento"/>
        </xs:sequence>
        <xs:attribute name="descricao" type="xs:string" use="optional"/>
    </xs:complexType>

    <xs:simpleType name="Documento">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:complexType name="Custos">
        <xs:sequence>
            <xs:element name="default" type="CasoDeCustos"/>
            <xs:element name="caso" type="CasoDeCustos" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="CasoDeCustos">
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="custo" type="Custo" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="descricao" type="xs:string" use="optional"/>
    </xs:complexType>

    <xs:complexType name="Custo">
        <xs:sequence>
            <xs:element name="descricao" type="DescricaoDoCusto"/>
            <xs:element name="moeda" type="Moeda"/>
            <xs:element name="valor" type="Valor"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="DescricaoDoCusto">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:simpleType name="Moeda">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:simpleType name="Valor">
        <xs:restriction base="xs:string"/>
        <!-- TODO: restringir usando expressão regular para aceitar números e vírgula separando os centavos -->
    </xs:simpleType>

    <xs:complexType name="CanaisDePrestacao">
        <xs:sequence>
            <xs:element name="default" type="CasoDeCanaisDePrestacao"/>
            <xs:element name="caso" type="CasoDeCanaisDePrestacao" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="CasoDeCanaisDePrestacao">
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="canal-de-prestacao" type="CanalDePrestacao"/>
        </xs:sequence>
        <xs:attribute name="descricao" type="xs:string" use="optional"/>
    </xs:complexType>

    <xs:complexType name="CanalDePrestacao">
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="descricao" type="DescricaoDeCanalDePrestacao"/>
        </xs:sequence>
        <xs:attribute name="tipo" type="TipoDeCanalDePrestacao" use="required"/>
    </xs:complexType>

    <xs:simpleType name="DescricaoDeCanalDePrestacao">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:simpleType name="TipoDeCanalDePrestacao">
        <xs:restriction base="xs:string">
            <xs:enumeration value="web"/>
            <xs:enumeration value="web-agendar"/>
            <xs:enumeration value="web-inscrever-se"/>
            <xs:enumeration value="web-simular"/>
            <xs:enumeration value="web-calcular-taxas"/>
            <xs:enumeration value="web-acompanhar"/>
            <xs:enumeration value="web-consultar"/>
            <xs:enumeration value="web-emitir"/>
            <xs:enumeration value="web-preencher"/>
            <xs:enumeration value="web-declarar"/>
            <xs:enumeration value="presencial"/>
            <xs:enumeration value="telefone"/>
            <xs:enumeration value="e-mail"/>
            <xs:enumeration value="postal"/>
            <xs:enumeration value="aplicativo-movel"/>
            <xs:enumeration value="sms"/>
            <xs:enumeration value="fax"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="Orgao">
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="SegmentosDaSociedade">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="item" type="SegmentoDaSociedade"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="SegmentoDaSociedade">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Cidadãos"/>
            <xs:enumeration value="Empresas"/>
            <xs:enumeration value="Órgãos e entidades públicas"/>
            <xs:enumeration value="Demais segmentos (ONGs, organizações sociais, etc)"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="EventosDaLinhaDaVida">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="item" type="EventoDaLinhaDaVida"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="EventoDaLinhaDaVida">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Apoio financeiro e crédito"/>
            <xs:enumeration value="Aposentadoria"/>
            <xs:enumeration value="Contas e Impostos"/>
            <xs:enumeration value="Cuidados com a saúde"/>
            <xs:enumeration value="Documentos e certidões"/>
            <xs:enumeration value="Empreendedorismo e negócios"/>
            <xs:enumeration value="Estrangeiros no Brasil"/>
            <xs:enumeration value="Estudos"/>
            <xs:enumeration value="Exportação de produtos e serviços"/>
            <xs:enumeration value="Família"/>
            <xs:enumeration value="Importação de produtos e serviços"/>
            <xs:enumeration value="Imóveis"/>
            <xs:enumeration value="Profissão e trabalho"/>
            <xs:enumeration value="Veículos"/>
            <xs:enumeration value="Viagem ao exterior"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="AreasDeInteresse">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="item" type="AreaDeInteresse"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="AreaDeInteresse">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Abastecimento"/>
            <xs:enumeration value="Administração financeira"/>
            <xs:enumeration value="Agricultura orgânica"/>
            <xs:enumeration value="Agropecuária"/>
            <xs:enumeration value="Águas"/>
            <xs:enumeration value="Alimento"/>
            <xs:enumeration value="Ambiente e saúde"/>
            <xs:enumeration value="Comunicações"/>
            <xs:enumeration value="Comércio e Serviços"/>
            <xs:enumeration value="Economia e Finanças"/>
            <xs:enumeration value="Educação"/>
            <xs:enumeration value="Educação básica"/>
            <xs:enumeration value="Educação superior"/>
            <xs:enumeration value="Educação à distância"/>
            <xs:enumeration value="Emergências e Urgências"/>
            <xs:enumeration value="Encargos financeiros"/>
            <xs:enumeration value="Esporte e Lazer"/>
            <xs:enumeration value="Finanças"/>
            <xs:enumeration value="Habitação"/>
            <xs:enumeration value="Humanização na saúde"/>
            <xs:enumeration value="Indústria"/>
            <xs:enumeration value="Meio ambiente"/>
            <xs:enumeration value="Pecuária"/>
            <xs:enumeration value="Pessoa"/>
            <xs:enumeration value="Previdência Social"/>
            <xs:enumeration value="Profissionais da educação"/>
            <xs:enumeration value="Proteção social"/>
            <xs:enumeration value="Qualidade ambiental"/>
            <xs:enumeration value="Relações Internacionais"/>
            <xs:enumeration value="Saúde"/>
            <xs:enumeration value="Saúde da criança"/>
            <xs:enumeration value="Saúde da família"/>
            <xs:enumeration value="Saúde da mulher"/>
            <xs:enumeration value="Saúde do homem"/>
            <xs:enumeration value="Saúde do idoso"/>
            <xs:enumeration value="Saúde dos portadores de deficiências"/>
            <xs:enumeration value="Segurança e Ordem Pública"/>
            <xs:enumeration value="Trabalho"/>
            <xs:enumeration value="Transportes"/>
            <xs:enumeration value="Turismo"/>
            <xs:enumeration value="Urbanismo"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="PalavrasChave">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="item" type="PalavraChave"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="PalavraChave">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:complexType name="Legislacoes">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="item" type="Legislacao"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="Legislacao">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

</xs:schema>

=== servicosgovbr/cartas-de-servico/cartas-servico/v3/servicos/pagamento-de-darf-da-secretaria-de-patrimonio-da-uniao.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<servico xmlns="http://servicos.gov.br/v3/schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://servicos.gov.br/v3/schema ../servico.xsd">
    <nome>PagarDarf da Secretaria de Patrimônio da União</nome>
    <sigla/>
    <nomes-populares/>
    <descricao><![CDATA[O Documento de Arrecadação de Receitas Federais – DARF é utilizado para recolhimento, junto aos bancos autorizados, da taxa de ocupação ou foro dos imóveis da União, além de outros débitos de caráter extraordinário. Nele serão impressos os dados de identificação do imóvel, do titular ocupante ou foreiro, a data de pagamento e os respectivos valores, a serem recolhidos ao Tesouro Nacional.]]></descricao>
    <contato/>
    <gratuito>false</gratuito>
    <solicitantes>
        <solicitante>
            <tipo>Usuários de imóveis da união</tipo>
            <requisitos/>
        </solicitante>
    </solicitantes>
    <tempo-total-estimado>
        <descricao/>
    </tempo-total-estimado>
    <etapas>
        <etapa>
            <titulo>Pagamento de Darf</titulo>
            <descricao/>
            <documentos>
                <default>
                    <item>RIP</item>
                    <item>cpf ou cnpj</item>
                </default>
            </documentos>
            <custos>
                <default/>
            </custos>
            <canais-de-prestacao>
                <default/>
            </canais-de-prestacao>
        </etapa>
    </etapas>
    <orgao id=""/>
    <segmentos-da-sociedade/>
    <areas-de-interesse/>
    <palavras-chave/>
    <legislacoes/>
</servico>

=== servicosgovbr/cartas-de-servico/cartas-servico/v3/servicos/extrato-do-processamento-da-dipj.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<servico xmlns="http://servicos.gov.br/v3/schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://servicos.gov.br/v3/schema ../servico.xsd">
    <nome>Extrato do Processamento da DIPJ</nome>
    <sigla/>
    <nomes-populares/>
    <descricao>Visualizar a relação das últimas declarações DIPJ (Declaração de Informações Econômico-Fiscais da Pessoa Jurídica) entregues e realizar algumas consultas específicas.

* [Mais informações](http://www.receita.fazenda.gov.br/PessoaJuridica/DIPJ/2013/PergResp/default.htm): Orientações gerais sobre o serviço

* [Serviços relacionados](http://www.receita.fazenda.gov.br/aplicacoes/atbhe/tus/default.aspx?/a/6): Ver todos os serviços do assunto "Declarações e Demonstrativos"</descricao>
    <gratuito/>
    <solicitantes/>
    <tempo-total-estimado>
        <descricao/>
    </tempo-total-estimado>
    <etapas>
        <etapa>
            <titulo/>
            <descricao/>
            <documentos>
                <default/>
            </documentos>
            <custos>
                <default/>
            </custos>
            <canais-de-prestacao>
                <default>
                    <canal-de-prestacao tipo="web">
                        <descricao>https://www.receita.fazenda.gov.br/Aplicacoes/SSL/ATRJO/consProcess/Index.asp</descricao>
                    </canal-de-prestacao>
                    <canal-de-prestacao tipo="web">
                        <descricao>[Internet (via Portal e-CAC com certificado digital)](https://cav.receita.fazenda.gov.br/eCAC/publico/login.aspx?sistema=00013)</descricao>
                    </canal-de-prestacao>
                </default>
            </canais-de-prestacao>
        </etapa>
    </etapas>
    <orgao id="secretaria-da-receita-federal-do-brasil-rfb"/>
    <segmentos-da-sociedade>
        <item>Empresas</item>
    </segmentos-da-sociedade>
    <areas-de-interesse>
        <item>Economia e Finanças</item>
    </areas-de-interesse>
    <palavras-chave/>
    <legislacoes/>
</servico>

=== servicosgovbr/cartas-de-servico/cartas-servico/v3/servicos/exclusao-do-simples-nacional.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<servico xmlns="http://servicos.gov.br/v3/schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://servicos.gov.br/v3/schema ../servico.xsd">
    <nome>Exclusão do Simples Nacional</nome>
    <sigla/>
    <nomes-populares/>
    <descricao>Comunicar a exclusão do Simples Nacional.
</descricao>
    <gratuito/>
    <solicitantes/>
    <tempo-total-estimado>
        <descricao/>
    </tempo-total-estimado>
    <etapas>
        <etapa>
            <titulo/>
            <descricao/>
            <documentos>
                <default/>
            </documentos>
            <custos>
                <default/>
            </custos>
            <canais-de-prestacao>
                <default>
                    <canal-de-prestacao tipo="web">
                        <descricao>http://www8.receita.fazenda.gov.br/SIMPLESNACIONAL/Servicos/Grupo.aspx?grp=6</descricao>
                    </canal-de-prestacao>
                </default>
            </canais-de-prestacao>
        </etapa>
    </etapas>
    <orgao id="secretaria-da-receita-federal-do-brasil-rfb"/>
    <segmentos-da-sociedade>
        <item>Empresas</item>
    </segmentos-da-sociedade>
    <areas-de-interesse>
        <item>Economia e Finanças</item>
    </areas-de-interesse>
    <palavras-chave/>
    <legislacoes/>
</servico>

=== servicosgovbr/cartas-de-servico/cartas-servico/v3/servicos/renda-variavel-alienacao-de-acoes-ouro-e-ativo-financeiro.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<servico xmlns="http://servicos.gov.br/v3/schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://servicos.gov.br/v3/schema ../servico.xsd">
    <nome>Renda Variável, Alienação de Ações, Ouro e Ativo Financeiro</nome>
    <sigla/>
    <nomes-populares/>
    <descricao>Acessar o programa Renda Variável, Alienação de Ações, Ouro e Ativos Financeiros para download (anos de 2001 a 2004).
</descricao>
    <gratuito/>
    <solicitantes/>
    <tempo-total-estimado>
        <descricao/>
    </tempo-total-estimado>
    <etapas>
        <etapa>
            <titulo/>
            <descricao/>
            <documentos>
                <default/>
            </documentos>
            <custos>
                <default/>
            </custos>
            <canais-de-prestacao>
                <default>
                    <canal-de-prestacao tipo="web">
                        <descricao>http://www.receita.fazenda.gov.br/PessoaFisica/RendaVariavel/default.htm</descricao>
                    </canal-de-prestacao>
                </default>
            </canais-de-prestacao>
        </etapa>
    </etapas>
    <orgao id="secretaria-da-receita-federal-do-brasil-rfb"/>
    <segmentos-da-sociedade>
        <item>Cidadãos</item>
    </segmentos-da-sociedade>
    <areas-de-interesse>
        <item>Economia e Finanças</item>
    </areas-de-interesse>
    <palavras-chave/>
    <legislacoes/>
</servico>

=== servicosgovbr/cartas-de-servico/cartas-servico/v3/servicos/obter-aprovacao-do-boletim-mensal-de-producao.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<servico xsi:schemaLocation="http://servicos.gov.br/v3/schema.../servico.xsd" xmlns="http://servicos.gov.br/v3/schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <id>obter-aprovacao-do-boletim-mensal-de-producao</id>
    <dbId>3331</dbId>
    <nome>Obter aprovação do Boletim Mensal de Produção</nome>
    <sigla></sigla>
    <descricao>Consiste em: (i) receber dos Operadores de Contrato de Contrato de Concessão, Partilha e Cessão Onerosa a(s) o BMP; (ii) analisar o BMP; e (iii) publicar no site da ANP o ato administrativo.</descricao>
    <contato></contato>
    <gratuito>true</gratuito>
    <porcentagem-manual>false</porcentagem-manual>
    <servico-digital>false</servico-digital>
    <link-servico-digital></link-servico-digital>
    <solicitantes>
        <solicitante id="3918">
            <tipo>Operadores de Contrato de Contrato de Concessão, Partilha e Cessão Onerosa</tipo>
            <requisitos></requisitos>
        </solicitante>
    </solicitantes>
    <tempo-total-estimado>
        <entre min="31" max="60" unidade="dias-corridos"/>
        <descricao></descricao>
    </tempo-total-estimado>
    <validade-documento>
        <descricao></descricao>
    </validade-documento>
    <etapas>
        <etapa id="7447">
            <titulo>Solicitar aprovação</titulo>
            <descricao></descricao>
            <documentos>
                <default>
                    <item id="10567">Boletim Mensal de Produção</item>
                </default>
            </documentos>
            <custos>
                <default/>
            </custos>
            <canais-de-prestacao>
                <default>
                    <canal-de-prestacao id="7885" tipo="presencial">
                        <descricao>**Agência Nacional de Petróleo, Gás Natural e Biocombustíveis** - Av. Rio Branco, 65 / 22º andar - 20090-004 - Rio de Janeiro - RJ</descricao>
                    </canal-de-prestacao>
                </default>
            </canais-de-prestacao>
        </etapa>
    </etapas>
    <orgao id="http://estruturaorganizacional.dados.gov.br/id/unidade-organizacional/25281" dbId="917">
        <nomeOrgao>Agência Nacional do Petróleo, Gás Natural e Biocombustíveis (ANP)</nomeOrgao>
    </orgao>
    <segmentos-da-sociedade>
        <item idSegmento="3" idServicoSegmento="7373">Empresas</item>
    </segmentos-da-sociedade>
    <areas-de-interesse>
        <item>Energia</item>
    </areas-de-interesse>
    <palavras-chave>
        <item id="13706">anp</item>
        <item id="13707">aprovação</item>
        <item id="13708">boletim mensal</item>
    </palavras-chave>
</servico>
