=== servicosgovbr/cartas-de-servico/cartas-servico/v3/servico.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://servicos.gov.br/v3/schema"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://servicos.gov.br/v3/schema"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified"
           version="1.0">

    <xs:element name="servico" type="Servico"/>
    <xs:complexType name="Servico">
        <xs:sequence>
            <xs:element name="nome" type="NomeDoServico"/>
            <xs:element name="sigla" type="Sigla"/>
            <xs:element name="nomes-populares" type="NomesPopulares"/>
            <xs:element name="descricao" type="DescricaoDoServico"/>
            <xs:element name="gratuito" type="Gratuito"/>
            <xs:element name="solicitantes" type="Solicitantes"/>
            <xs:element name="tempo-total-estimado" type="TempoTotalEstimado"/>
            <xs:element name="etapas" type="Etapas"/>
            <xs:element name="orgao" type="Orgao"/>
            <xs:element name="segmentos-da-sociedade" type="SegmentosDaSociedade"/>
            <xs:element name="eventos-da-linha-da-vida" type="EventosDaLinhaDaVida"/>
            <xs:element name="areas-de-interesse" type="AreasDeInteresse"/>
            <xs:element name="palavras-chave" type="PalavrasChave"/>
            <xs:element name="legislacoes" type="Legislacoes"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="NomeDoServico">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:simpleType name="Sigla">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:complexType name="NomesPopulares">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="item" type="NomePopular"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="NomePopular">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:simpleType name="DescricaoDoServico">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:simpleType name="Gratuito">
        <xs:restriction base="xs:string">
            <xs:enumeration value=""/>
            <xs:enumeration value="true"/>
            <xs:enumeration value="false"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="Solicitantes">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="solicitante" type="Solicitante"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Solicitante">
        <xs:sequence>
            <xs:element name="tipo" type="TipoDeSolicitante"/>
            <xs:element name="requisitos" type="Requisitos"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="TipoDeSolicitante">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:simpleType name="Requisitos">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:complexType name="TempoTotalEstimado">
        <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="1">
                <xs:element name="entre" type="Entre"/>
                <xs:element name="ate" type="Ate"/>
            </xs:choice>
            <xs:element name="descricao" type="DescricaoDoTempoTotalEstimado"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Entre">
        <xs:attribute name="min" type="UnidadeDeTempo" use="required"/>
        <xs:attribute name="max" type="UnidadeDeTempo" use="required"/>
        <xs:attribute name="unidade" type="TipoDeTempoTotalEstimado" use="required"/>
    </xs:complexType>

    <xs:complexType name="Ate">
        <xs:attribute name="max" type="UnidadeDeTempo" use="required"/>
        <xs:attribute name="unidade" type="TipoDeTempoTotalEstimado" use="required"/>
    </xs:complexType>

    <xs:simpleType name="TipoDeTempoTotalEstimado">
        <xs:restriction base="xs:string">
            <xs:enumeration value="minutos"/>
            <xs:enumeration value="horas"/>
            <xs:enumeration value="dias"/>
            <xs:enumeration value="dias-corridos"/>
            <xs:enumeration value="dias-uteis"/>
            <xs:enumeration value="meses"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="UnidadeDeTempo">
        <xs:restriction base="xs:nonNegativeInteger"/>
    </xs:simpleType>

    <xs:simpleType name="DescricaoDoTempoTotalEstimado">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:complexType name="Etapas">
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="etapa" type="Etapa"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Etapa">
        <xs:sequence>
            <xs:element name="titulo" type="Titulo"/>
            <xs:element name="descricao" type="DescricaoDaEtapa"/>
            <xs:element name="documentos" type="Documentos"/>
            <xs:element name="custos" type="Custos"/>
            <xs:element name="canais-de-prestacao" type="CanaisDePrestacao"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="Titulo">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:simpleType name="DescricaoDaEtapa">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:complexType name="Documentos">
        <xs:sequence>
            <xs:element name="default" type="CasoDeDocumentos"/>
            <xs:element name="caso" type="CasoDeDocumentos" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="CasoDeDocumentos">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="item" type="Documento"/>
        </xs:sequence>
        <xs:attribute name="descricao" type="xs:string" use="optional"/>
    </xs:complexType>

    <xs:simpleType name="Documento">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:complexType name="Custos">
        <xs:sequence>
            <xs:element name="default" type="CasoDeCustos"/>
            <xs:element name="caso" type="CasoDeCustos" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="CasoDeCustos">
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="custo" type="Custo" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="descricao" type="xs:string" use="optional"/>
    </xs:complexType>

    <xs:complexType name="Custo">
        <xs:sequence>
            <xs:element name="descricao" type="DescricaoDoCusto"/>
            <xs:element name="moeda" type="Moeda"/>
            <xs:element name="valor" type="Valor"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="DescricaoDoCusto">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:simpleType name="Moeda">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:simpleType name="Valor">
        <xs:restriction base="xs:string"/>
        <!-- TODO: restringir usando expressão regular para aceitar números e vírgula separando os centavos -->
    </xs:simpleType>

    <xs:complexType name="CanaisDePrestacao">
        <xs:sequence>
            <xs:element name="default" type="CasoDeCanaisDePrestacao"/>
            <xs:element name="caso" type="CasoDeCanaisDePrestacao" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="CasoDeCanaisDePrestacao">
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="canal-de-prestacao" type="CanalDePrestacao"/>
        </xs:sequence>
        <xs:attribute name="descricao" type="xs:string" use="optional"/>
    </xs:complexType>

    <xs:complexType name="CanalDePrestacao">
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="descricao" type="DescricaoDeCanalDePrestacao"/>
        </xs:sequence>
        <xs:attribute name="tipo" type="TipoDeCanalDePrestacao" use="required"/>
    </xs:complexType>

    <xs:simpleType name="DescricaoDeCanalDePrestacao">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:simpleType name="TipoDeCanalDePrestacao">
        <xs:restriction base="xs:string">
            <xs:enumeration value="web"/>
            <xs:enumeration value="web-agendar"/>
            <xs:enumeration value="web-inscrever-se"/>
            <xs:enumeration value="web-simular"/>
            <xs:enumeration value="web-calcular-taxas"/>
            <xs:enumeration value="web-acompanhar"/>
            <xs:enumeration value="web-consultar"/>
            <xs:enumeration value="web-emitir"/>
            <xs:enumeration value="web-preencher"/>
            <xs:enumeration value="web-declarar"/>
            <xs:enumeration value="presencial"/>
            <xs:enumeration value="telefone"/>
            <xs:enumeration value="e-mail"/>
            <xs:enumeration value="postal"/>
            <xs:enumeration value="aplicativo-movel"/>
            <xs:enumeration value="sms"/>
            <xs:enumeration value="fax"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="Orgao">
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="SegmentosDaSociedade">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="item" type="SegmentoDaSociedade"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="SegmentoDaSociedade">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Cidadãos"/>
            <xs:enumeration value="Empresas"/>
            <xs:enumeration value="Órgãos e entidades públicas"/>
            <xs:enumeration value="Demais segmentos (ONGs, organizações sociais, etc)"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="EventosDaLinhaDaVida">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="item" type="EventoDaLinhaDaVida"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="EventoDaLinhaDaVida">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Apoio financeiro e crédito"/>
            <xs:enumeration value="Aposentadoria"/>
            <xs:enumeration value="Contas e Impostos"/>
            <xs:enumeration value="Cuidados com a saúde"/>
            <xs:enumeration value="Documentos e certidões"/>
            <xs:enumeration value="Empreendedorismo e negócios"/>
            <xs:enumeration value="Estrangeiros no Brasil"/>
            <xs:enumeration value="Estudos"/>
            <xs:enumeration value="Exportação de produtos e serviços"/>
            <xs:enumeration value="Família"/>
            <xs:enumeration value="Importação de produtos e serviços"/>
            <xs:enumeration value="Imóveis"/>
            <xs:enumeration value="Profissão e trabalho"/>
            <xs:enumeration value="Veículos"/>
            <xs:enumeration value="Viagem ao exterior"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="AreasDeInteresse">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="item" type="AreaDeInteresse"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="AreaDeInteresse">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Abastecimento"/>
            <xs:enumeration value="Administração financeira"/>
            <xs:enumeration value="Agricultura orgânica"/>
            <xs:enumeration value="Agropecuária"/>
            <xs:enumeration value="Águas"/>
            <xs:enumeration value="Alimento"/>
            <xs:enumeration value="Ambiente e saúde"/>
            <xs:enumeration value="Comunicações"/>
            <xs:enumeration value="Comércio e Serviços"/>
            <xs:enumeration value="Economia e Finanças"/>
            <xs:enumeration value="Educação"/>
            <xs:enumeration value="Educação básica"/>
            <xs:enumeration value="Educação superior"/>
            <xs:enumeration value="Educação à distância"/>
            <xs:enumeration value="Emergências e Urgências"/>
            <xs:enumeration value="Encargos financeiros"/>
            <xs:enumeration value="Esporte e Lazer"/>
            <xs:enumeration value="Finanças"/>
            <xs:enumeration value="Habitação"/>
            <xs:enumeration value="Humanização na saúde"/>
            <xs:enumeration value="Indústria"/>
            <xs:enumeration value="Meio ambiente"/>
            <xs:enumeration value="Pecuária"/>
            <xs:enumeration value="Pessoa"/>
            <xs:enumeration value="Previdência Social"/>
            <xs:enumeration value="Profissionais da educação"/>
            <xs:enumeration value="Proteção social"/>
            <xs:enumeration value="Qualidade ambiental"/>
            <xs:enumeration value="Relações Internacionais"/>
            <xs:enumeration value="Saúde"/>
            <xs:enumeration value="Saúde da criança"/>
            <xs:enumeration value="Saúde da família"/>
            <xs:enumeration value="Saúde da mulher"/>
            <xs:enumeration value="Saúde do homem"/>
            <xs:enumeration value="Saúde do idoso"/>
            <xs:enumeration value="Saúde dos portadores de deficiências"/>
            <xs:enumeration value="Segurança e Ordem Pública"/>
            <xs:enumeration value="Trabalho"/>
            <xs:enumeration value="Transportes"/>
            <xs:enumeration value="Turismo"/>
            <xs:enumeration value="Urbanismo"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="PalavrasChave">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="item" type="PalavraChave"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="PalavraChave">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:complexType name="Legislacoes">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="item" type="Legislacao"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="Legislacao">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

</xs:schema>

=== servicosgovbr/cartas-de-servico/cartas-servico/v3/servicos/credenciar-psicologo-para-emissao-de-comprovante-de-aptidao-psicologica-para-manuseio-de-armas-de-fogo.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<servico xsi:schemaLocation="http://servicos.gov.br/v3/schema.../servico.xsd" xmlns="http://servicos.gov.br/v3/schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <id>credenciar-psicologo-para-emissao-de-comprovante-de-aptidao-psicologica-para-manuseio-de-armas-de-fogo</id>
    <dbId>2350</dbId>
    <nome>Credenciar psicólogo para emissão de comprovante de aptidão psicológica para manuseio de armas de fogo</nome>
    <sigla></sigla>
    <nomes-populares>
        <item id="1911">Credenciamento de psicólogo para realizarem avaliação psicológica para manuseio de arma de fogo</item>
    </nomes-populares>
    <descricao>É o documento que autoriza psicólogos devidamente habilitados a realizar avaliações e emitir laudos para comprovação de aptidão psicológica para o manuseio de arma de fogo. Deve solicitar o credenciamento em uma unidade da PF mediante formulário próprio.</descricao>
    <contato></contato>
    <gratuito>true</gratuito>
    <porcentagem-manual>false</porcentagem-manual>
    <servico-digital>false</servico-digital>
    <link-servico-digital></link-servico-digital>
    <solicitantes>
        <solicitante id="2904">
            <tipo>Psicólogos, empresas e instituições que precisam expedir o comprovante de aptidão psicológica para manuseio de armas de fogo.</tipo>
            <requisitos></requisitos>
        </solicitante>
    </solicitantes>
    <tempo-total-estimado>
        <nao-estimado-ainda/>
        <descricao></descricao>
    </tempo-total-estimado>
    <validade-documento>
        <descricao></descricao>
    </validade-documento>
    <etapas>
        <etapa id="5659">
            <titulo>Requerer credenciamento</titulo>
            <descricao>Para obter modelo do formulário, clique [aqui](http://www.pf.gov.br/servicos-pf/armas/credenciamento-psicologos/requerimento-para-credenciamento-de-psicologo.pdf)</descricao>
            <documentos>
                <default>
                    <item id="6616">Carteira de identidade</item>
                    <item id="6617">Carteira de trabalho</item>
                    <item id="6618">Certificado de antecedentes criminais fornecidas pela Justiça Federal, Estadual, Militar e Eleitoral e de não estar respondendo a inquérito policial ou a processo criminal, que poderão ser fornecidas por meios eletrônicos.</item>
                    <item id="6619">Certificado de conclusão de curso</item>
                    <item id="6620">Comprovante de quitação eleitoral</item>
                    <item id="6621">CPF</item>
                    <item id="6622">Diploma</item>
                    <item id="6623">Fotos do consultório/Clinica</item>
                    <item id="6624">Documentação legal do consultório/clínica</item>
                    <item id="6631">Formulário preenchido</item>
                    <item id="6632">Foto 3x4 recente</item>
                    <item id="6633">Comprovante de inscrição ativa e regular no Conselho Regional de Psicologia e certidão negativa de infrações éticas do respectivo Conselho</item>
                    <item id="6634">Comprovante de que possui pelo menos dois anos de efetivo exercício na profissão de psicólogo;</item>
                    <item id="6635">Certificado que ateste sua aptidão para a aplicação dos instrumentos psicológicos previstos nos incisos I e II do art. 5º da IN 78/2014-DG/PF (testes expressivo e projetivo)</item>
                </default>
            </documentos>
            <custos>
                <default/>
            </custos>
            <canais-de-prestacao>
                <default>
                    <canal-de-prestacao id="5490" tipo="presencial">
                        <descricao>Em uma [Superintendência ou Delegacia da Polícia Federal](http://www.pf.gov.br/institucional/unidades/superintendencias-e-delegacias)</descricao>
                    </canal-de-prestacao>
                </default>
            </canais-de-prestacao>
        </etapa>
        <etapa id="5660">
            <titulo>Participar  das entrevistas</titulo>
            <descricao></descricao>
            <documentos>
                <default>
                    <item id="6625">Carteira de identidade</item>
                    <item id="6626">Carteira de trabalho</item>
                </default>
            </documentos>
            <custos>
                <default/>
            </custos>
            <canais-de-prestacao>
                <default>
                    <canal-de-prestacao id="5491" tipo="presencial">
                        <descricao>Em uma [Superintendência ou Delegacia da Polícia Federal](http://www.pf.gov.br/institucional/unidades/superintendencias-e-delegacias)</descricao>
                    </canal-de-prestacao>
                </default>
            </canais-de-prestacao>
        </etapa>
        <etapa id="5661">
            <titulo>Agendar retirada do documento</titulo>
            <descricao></descricao>
            <documentos>
                <default>
                    <item id="6627">Carteira de identidade</item>
                    <item id="6628">Carteira de trabalho</item>
                </default>
            </documentos>
            <custos>
                <default/>
            </custos>
            <canais-de-prestacao>
                <default>
                    <canal-de-prestacao id="5492" tipo="presencial">
                        <descricao>Em uma [Superintendência ou Delegacia da Polícia Federal](http://www.pf.gov.br/institucional/unidades/superintendencias-e-delegacias)</descricao>
                    </canal-de-prestacao>
                </default>
            </canais-de-prestacao>
        </etapa>
        <etapa id="5662">
            <titulo>Receber documentos</titulo>
            <descricao></descricao>
            <documentos>
                <default>
                    <item id="6629">Carteira de identidade</item>
                    <item id="6630">Carteira de trabalho</item>
                </default>
            </documentos>
            <custos>
                <default/>
            </custos>
            <canais-de-prestacao>
                <default>
                    <canal-de-prestacao id="5493" tipo="presencial">
                        <descricao>Em uma [Superintendência ou Delegacia da Polícia Federal](http://www.pf.gov.br/institucional/unidades/superintendencias-e-delegacias)</descricao>
                    </canal-de-prestacao>
                </default>
            </canais-de-prestacao>
        </etapa>
    </etapas>
    <orgao id="http://estruturaorganizacional.dados.gov.br/id/unidade-organizacional/316" dbId="37532">
        <nomeOrgao>Ministério da Justiça e Segurança Pública (MJSP)</nomeOrgao>
    </orgao>
    <segmentos-da-sociedade>
        <item idSegmento="1" idServicoSegmento="5622">Cidadãos</item>
        <item idSegmento="3" idServicoSegmento="5623">Empresas</item>
        <item idSegmento="2" idServicoSegmento="5624">Órgãos e entidades públicas</item>
    </segmentos-da-sociedade>
    <areas-de-interesse>
        <item>Fiscalização do Estado</item>
        <item>Segurança e Ordem Pública</item>
        <item>Saúde</item>
        <item>Defesa militar</item>
    </areas-de-interesse>
    <palavras-chave>
        <item id="10756">psicologia</item>
        <item id="10757">estatuto do desarmamento</item>
        <item id="10758">credenciamento</item>
    </palavras-chave>
</servico>

=== servicosgovbr/cartas-de-servico/cartas-servico/v3/servicos/extratos-de-pagamentos-de-beneficios-previdenciarios.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<servico xmlns="http://servicos.gov.br/v3/schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://servicos.gov.br/v3/schema ../servico.xsd">
    <nome>Extratos de pagamentos de benefícios Previdenciários</nome>
    <sigla/>
    <nomes-populares/>
    <descricao>Emite o extrato dos pagamentos recebidos pelo beneficiário previdenciários, junto ao INSS.

* [Telefone](undefined): Ligue 135 para obter mais informações.</descricao>
    <gratuito/>
    <solicitantes/>
    <tempo-total-estimado>
        <descricao/>
    </tempo-total-estimado>
    <etapas>
        <etapa>
            <titulo/>
            <descricao/>
            <documentos>
                <default/>
            </documentos>
            <custos>
                <default/>
            </custos>
            <canais-de-prestacao>
                <default>
                    <canal-de-prestacao tipo="web">
                        <descricao>http://agencia.previdencia.gov.br/e-aps/servico/144</descricao>
                    </canal-de-prestacao>
                </default>
            </canais-de-prestacao>
        </etapa>
    </etapas>
    <orgao id="ministerio-da-previdencia-social-mps"/>
    <segmentos-da-sociedade>
        <item>Cidadãos</item>
    </segmentos-da-sociedade>
    <areas-de-interesse>
        <item>Previdência Social</item>
    </areas-de-interesse>
    <palavras-chave/>
    <legislacoes/>
</servico>

=== servicosgovbr/cartas-de-servico/cartas-servico/v3/servicos/realizacao-de-recurso-contra-aplicacao-de-multa-dnit.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<servico xmlns="http://servicos.gov.br/v3/schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://servicos.gov.br/v3/schema ../servico.xsd">
    <nome><![CDATA[Realização de Recurso Contra Aplicação de Multa - DNIT]]></nome>
    <sigla>Recurso</sigla>
    <nomes-populares>
        <item>Recurso de Multa</item>
    </nomes-populares>
    <descricao><![CDATA[Processo administrativo, através do qual o interessado ou seu representante manifesta sua discordância da multa aplicada.]]></descricao>
    <contato/>
    <gratuito>true</gratuito>
    <solicitantes>
        <solicitante>
            <tipo>Qualquer cidadão que receba uma notificação de penalidade</tipo>
            <requisitos><![CDATA[Ter recebido a notificação de penalidade de uma multa DNIT]]></requisitos>
        </solicitante>
    </solicitantes>
    <tempo-total-estimado>
        <descricao><![CDATA[O prazo para interpor o recurso será aquele constante na notificação de penalidade para recolhimento de seu valor, não sendo este inferior a 30 (trinta) dias contados da data da notificação, isto é, da data em que o infrator recebeu a notificação de penalidade em seu domicílio, conforme determina o Art. 282 §4º, do [CTB](http://www.planalto.gov.br/ccivil_03/leis/L9503Compilado.htm)]]></descricao>
    </tempo-total-estimado>
    <etapas>
        <etapa>
            <titulo>Preencher formulário de recurso</titulo>
            <descricao><![CDATA[O condutor deve apresentar os fatos que achar prudentes para anular a penalidade.]]></descricao>
            <documentos>
                <default/>
            </documentos>
            <custos>
                <default/>
            </custos>
            <canais-de-prestacao>
                <default>
                    <canal-de-prestacao tipo="web">
                        <descricao><![CDATA[http://www.dnit.gov.br/rodovias/operacoes-rodoviarias/multas/multas-de-transito-aplicadas-pelo-dnit]]></descricao>
                    </canal-de-prestacao>
                </default>
            </canais-de-prestacao>
        </etapa>
    </etapas>
    <orgao id=""/>
    <segmentos-da-sociedade/>
    <areas-de-interesse/>
    <palavras-chave/>
    <legislacoes/>
</servico>

=== servicosgovbr/cartas-de-servico/cartas-servico/v3/servicos/certificado-de-licenca-de-funcionamento-clf-produtos-quimicos.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<servico xmlns="http://servicos.gov.br/v3/schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://servicos.gov.br/v3/schema ../servico.xsd">
    <nome>Certificado de Licença de Funcionamento (CLF) - Produtos Químicos</nome>
    <sigla/>
    <nomes-populares/>
    <descricao>É o documento que certifica que a pessoa jurídica em situação regular, ou pessoa física no caso de produtor rural, está devidamente registrada na Divisão de Controle de Produtos Químicos do Departamento de Polícia Federal.

Para obtê-lo, baixe o Programa Cadastro (vide "Formulários"), preencha as informações solicitadas de acordo com a Portaria 1.274/2003 (vide "Outros"), gere o arquivo com extensão XML que deverá ser salvo em um disquete ou CD, imprima o requerimento, e entregue-o juntamente com toda a documentação necessária em uma unidade da Polícia Federal (vide "Presencial").

* [Formulários](http://www.dpf.gov.br/servicos/gru/produtos-quimicos): GRU (FUNAD)

* [Formulários](http://www.dpf.gov.br/servicos/produtos-quimicos/programas/programa-cadastro): Programa Cadastro

* [Outros](http://www.dpf.gov.br/servicos/produtos-quimicos/legislacao/PORTARIA1274.pdf): Portaria 1.274/2003

* [Serviços relacionados](http://www.dpf.gov.br/servicos/produtos-quimicos/cadastro-e-licenca/renovacao-de-certificado-de-licenca-de-funcionamento): Renovação de Certificado de Licença de Funcionamento - CLF

* [Serviços relacionados](http://www.dpf.gov.br/servicos/produtos-quimicos/cadastro-e-licenca/atualizacao-de-produtos-quimicos): Atualização Cadastral de Produtos Químicos - Inclusão / Exclusão

* [Serviços relacionados](http://www.dpf.gov.br/servicos/produtos-quimicos/consultas/acompanhamento-de-processos): Acompanhamento de processos</descricao>
    <gratuito/>
    <solicitantes/>
    <tempo-total-estimado>
        <descricao/>
    </tempo-total-estimado>
    <etapas>
        <etapa>
            <titulo/>
            <descricao/>
            <documentos>
                <default/>
            </documentos>
            <custos>
                <default/>
            </custos>
            <canais-de-prestacao>
                <default>
                    <canal-de-prestacao tipo="web">
                        <descricao>http://www.dpf.gov.br/institucional/pf-pelo-brasil</descricao>
                    </canal-de-prestacao>
                </default>
            </canais-de-prestacao>
        </etapa>
    </etapas>
    <orgao id="ministerio-da-justica-mj"/>
    <segmentos-da-sociedade>
        <item>Cidadãos</item>
        <item>Empresas</item>
    </segmentos-da-sociedade>
    <areas-de-interesse>
        <item>Segurança e Ordem Pública</item>
    </areas-de-interesse>
    <palavras-chave/>
    <legislacoes/>
</servico>
